#
# Steve Client make system. 
#   JUST USE THE TOP LEVEL BUILD SCRIPT.
#

.PHONY: build clean release

build:
	@echo "Compiling Client"

clean:
	@echo "Cleaning Client"

releaese:
	@echo "Building Client Release"


